import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db, isFirebaseConfigured } from './firebaseConfig';
import { AGE_REALMS } from '../../data/learning-path-data';
import { TypingParagraph, TypingParagraphDraftDoc, TypingParagraphSnapshotDoc } from '../../data/typing-paragraph-types';
import { generateParagraphsFromRealm } from '../typingParagraphLoader';

const getAutoGeneratedFallback = (realmId: string): TypingParagraph[] => {
  const realm = AGE_REALMS.find(r => r.id === realmId);
  return realm ? generateParagraphsFromRealm(realm) : [];
};

/**
 * Load draft paragraphs from Firestore `typing_paragraph_drafts/{realmId}`.
 * Fallbacks to auto-generated paragraphs from the realm's vocabulary if no draft exists.
 */
export const loadTypingParagraphDraft = async (
  realmId: string
): Promise<{ paragraphs: TypingParagraph[]; isCloudDraft: boolean; updatedAt?: any }> => {
  if (!isFirebaseConfigured || !db) {
    return { paragraphs: getAutoGeneratedFallback(realmId), isCloudDraft: false };
  }

  try {
    const draftDocRef = doc(db, 'typing_paragraph_drafts', realmId);
    const snap = await getDoc(draftDocRef);

    if (snap.exists()) {
      const data = snap.data() as TypingParagraphDraftDoc;
      if (Array.isArray(data.paragraphs)) {
        return { paragraphs: data.paragraphs, isCloudDraft: true, updatedAt: data.updatedAt };
      }
    }
  } catch (error) {
    console.warn('[TypingParagraphAdmin] Error fetching draft, falling back to auto-generated paragraphs:', error);
  }

  return { paragraphs: getAutoGeneratedFallback(realmId), isCloudDraft: false };
};

/**
 * Save draft changes to Firestore `typing_paragraph_drafts/{realmId}`
 */
export const saveTypingParagraphDraft = async (
  realmId: string,
  paragraphs: TypingParagraph[],
  authorEmail: string = 'admin'
): Promise<boolean> => {
  if (!isFirebaseConfigured || !db) {
    throw new Error('Firebase chưa được cấu hình.');
  }

  const draftDocRef = doc(db, 'typing_paragraph_drafts', realmId);
  const payload: TypingParagraphDraftDoc = {
    paragraphs,
    updatedBy: authorEmail,
    updatedAt: serverTimestamp()
  };
  await setDoc(draftDocRef, payload);

  return true;
};

/**
 * Publish snapshot to Firestore `typing_paragraph_snapshots/latest`
 */
export const publishTypingParagraphSnapshot = async (
  paragraphsByRealm: Record<string, TypingParagraph[]>,
  authorEmail: string = 'admin'
): Promise<string> => {
  if (!isFirebaseConfigured || !db) {
    throw new Error('Firebase chưa được cấu hình.');
  }

  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
  const timeStr = `${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;
  const versionId = `v${dateStr}_${timeStr}`;

  const payload: TypingParagraphSnapshotDoc = {
    versionId,
    publishedAt: serverTimestamp(),
    publishedBy: authorEmail,
    paragraphsByRealm
  };

  const snapshotDocRef = doc(db, 'typing_paragraph_snapshots', 'latest');
  await setDoc(snapshotDocRef, payload);

  // Also save a copy with version ID for historical rollback
  try {
    const historyDocRef = doc(db, 'typing_paragraph_snapshots', versionId);
    await setDoc(historyDocRef, payload);
  } catch (e) {
    // Non-critical
  }

  // Update local cache directly for seamless admin experience
  try {
    localStorage.setItem('typing_pew_pew_snapshot_version', versionId);
    localStorage.setItem('typing_pew_pew_snapshot_paragraphs', JSON.stringify(paragraphsByRealm));
  } catch (e) {
    // Ignore storage quota
  }

  return versionId;
};
